/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./pages/components/avatar.vue')['default']
    Card: typeof import('./pages/components/card.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FrostedGlass: typeof import('./components/FrostedGlass.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    RecommendCard: typeof import('./pages/components/recommendCard.vue')['default']
    RecommendedCards: typeof import('./pages/components/recommendedCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
